name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y g++
      - name: Build CPP files
        run: |
           find . -name "*.cpp" -type f -print0 | while read -d $'\0' file
           do
               g++ "$file" -o "${file%.*}"
           done
