name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake
      - name: Configure build
        run: cmake -S . -B build
      - name: Build project
        run: cmake --build build
